export { HeroSection } from "./hero-section";
export { WiseTrainerSection } from "./wisetrainer-section";
export { WiseTrainerAdvantagesSection } from "./wisetrainer-advantages-section";
export { TechnologySection } from "./technology-section";
export { BlogSection } from "./blog-section";
export { ContactSection } from "./contact-section";
export { ProfilesSection } from "./profiles-section";
export { FaqSection } from "./faq-section";
export { PlatformSection } from "./platform-section";